### ISSUE TITLE
Data synchronization 

### ISSUE THREAD

**Issue by Repulsiveprogress** [DS-Software/ULS#12]
Добавить возможность синхронизации данных с ULS на другие сервис, ник и аватар един везде. 
К этому добавить возможность добавлять свои поля, которые тоже можно синхронизировать.

**Comment by DSSoftware** [comment]
#11 is a part of this issue.

**Comment by DSSoftware** [comment]
Added Name, Surname, Nick and Birthday to users.
Planned to add scopes (External_Auth) and adjust new mail templates to work with this variables.

**Comment by DSSoftware** [comment]
Added scopes to external_auth.

**Comment by DSSoftware** [comment]
### Resolved
This issue will be resolved in the next release.
