### ISSUE TITLE
Add CAPTCHA

### ISSUE THREAD

**Issue by DSSoftware** [DS-Software/ULS#22]
Add CAPTCHA to restore password and register forms.

**Comment by Repulsiveprogress** [comment]
Капча, которая не требует прохождения картинок и ввода текста с символов*

**Comment by DSSoftware** [comment]
Эх, @KepchykS, не получилось.
Гугловская капча не совсем совместима, поэтому пришлось пилить свой вариант.

**Comment by Repulsiveprogress** [comment]
@DSSoftware Как это так? Она же вроде везде где можно встает.
Невидимка от Google отлично бы подошла, лучше по возможности попробовать использовать reCAPTCHA v3.

**В любом случае, нужно минимизировать использование капч и прочего ужаса.**

А если уж решились, что без невидимой капчи можно обойтись, гляньте решение hCaptcha. Пишут, молл, приватность пользователей превыше всего, да и деньги можно получать за прохождение капчи другими пользователями. Только плюсы при использовании.

**Выбор за вами** 🤷‍♂️

**Comment by DSSoftware** [comment]
> @DSSoftware Как это так? Она же вроде везде где можно встает. Невидимка от Google отлично бы подошла, лучше по возможности попробовать использовать reCAPTCHA v3.
> 
> **В любом случае, нужно минимизировать использование капч и прочего ужаса.**
> 
> А если уж решились, что без невидимой капчи можно обойтись, гляньте решение hCaptcha. Пишут, молл, приватность пользователей превыше всего, да и деньги можно получать за прохождение капчи другими пользователями. Только плюсы при использовании.
> 
> **Выбор за вами** 🤷‍♂️

Я подумаю об этом в будущем. На тот момент было проще добавить kcaptcha и не думать о проблемах с настройкой.
Но, скорее всего, я заменю на что-то лучшее.

**Comment by DSSoftware** [comment]
Проблема в том, что капчу нужно вызывать в определённое время в определённом месте.
![image](https://user-images.githubusercontent.com/56971105/186029214-8a6ad166-18ae-4070-9b60-6e26b63ea864.png)
А с google v2 ничего не получилось, т.к. она грузится при загрузке страницы, а не тогда когда её надо.

**Comment by DSSoftware** [comment]
А hcaptcha меня абсолютно бесит, т.к. у меня никогда не получается её пройти с первого раза :)

**Comment by DSSoftware** [comment]
@KepchykS если будут ещё идеи можете писать здесь.
Также, новая версия с такой капчей уже на основе, можете протестировать)

**Comment by DSSoftware** [comment]
@KepchykS можете радоваться :)
96c48f18293ccbde8a216920ca9a62d6c06c966d
Full Turnstile Support
#71

**Comment by DSSoftware** [comment]
Closing:
The issue will be fixed in the next release.
