### ISSUE TITLE
Add qr-code generation on the authorization page

### ISSUE THREAD

**Issue by Repulsiveprogress** [DS-Software/ULS#51]
Place a passwordless login block on the main account login page.  The code should be generated when the page loads, how it should look attached as an image below.

![image](https://user-images.githubusercontent.com/43721968/187987843-71b9d12e-ef61-49f9-acc0-7566ed45978d.png)

**_Optimize the generation code, if necessary to use additional resources, notify me._**

**Comment by DSSoftware** [comment]
+ Add special flag in config to disable this behavior.

**Comment by DSSoftware** [comment]
Added to the WIP list,

**Comment by DSSoftware** [comment]
Closing, as wontfix, as Easylogin was entirely replaced by Webauthn.
