### ISSUE TITLE
Автоматическая авторизация

### ISSUE THREAD

**Issue by Repulsiveprogress** [DS-Software/ULS#6]
Сделать автоматическую авторизации пользователя, после того, как он сменил пароль. Смена пароля через почту 🛑

**Comment by Repulsiveprogress** [comment]
Make automatic authorization of the user after they has changed password. Ю ноу?)

**Comment by DSSoftware** [comment]
### Section: UNAUTH
### Method: restore_password

**Comment by Repulsiveprogress** [comment]
Upd: смена пароля через почту

**Comment by DSSoftware** [comment]
А что, просто вставить код с verifyAuthChallenge в restore_password.

**Comment by DSSoftware** [comment]
И вообще, надо менять наименования методов.
Один метод verifyAuthChallenge - camel case
Другой - restore_password - snake case

**Comment by DSSoftware** [comment]
Пока такое сделать невозможно.

После решения проблемы #13, когда restore_password получит отдельный GUI, можно будет добавить там запрос к другому методу авторизации по данным restore_password. А пока, restore_password не имеет достаточно информации, чтобы авторизовать пользователя, либо придётся делать **серьёзные костыли**.

**Comment by DSSoftware** [comment]
Нууу...
Вполне возможно, что обойдёмся без костылей)
Сделал автоматический вход в регистрации, до смены пароля руки ещё не дошли.

**Comment by DSSoftware** [comment]
### Resolved
Эта функция будет реализована в новом исправлении.
