### ISSUE TITLE
Security | Change pass

### ISSUE THREAD

**Issue by Repulsiveprogress** [DS-Software/ULS#9]
Require the previous user password on password change.
### Method: changeUserPassword

- [x] Require old password on password change
- [x] Require old email verification on email change
- [x] Add support for long passwords in Users | changeUserPassword

**Comment by DSSoftware** [comment]
Actually, it's vulnerable to more issues as well.
It's possible to change user's email without email verification.
So, if you have access to a logged-in instance of ULS, you can fully steal the account.

**Comment by Repulsiveprogress** [comment]
CF)
